name: CI
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "CONTRIBUTORS"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "CONTRIBUTORS"
  workflow_dispatch: {}

jobs:
  test:
    name: Run audit and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
      - name: Format code and tidy modfile
        run: make tidy
      - name: Run audit checks
        run: make audit
      - name: Run unit tests
        run: make test
